/**
 * Emits src/game/words/wheels.data.ts — the frozen wheel table used by the
 * procedural level generator.
 *
 * A wheel is a 3–6 letter multiset (duplicates allowed) that every word on the
 * board must be spellable from. Wheels are derived from six-letter dictionary
 * words so each one is guaranteed at least one band-max answer, and are ranked
 * by pool size so the table order *is* the difficulty ladder.
 *
 * This table is committed. Never derive it at runtime: re-ranking it would
 * silently rewrite every generated level and invalidate existing saves.
 * Re-run only alongside a deliberate WHEEL_TABLE_VERSION bump.
 */
import { writeFileSync } from "node:fs";
import { SAFE_WORDS, dictionaryWordsFrom } from "../src/game/words/dictionary.ts";

const WHEEL_SIZE = 6;
const MIN_POOL = 6;

const letterKey = (word: string): string => [...word].sort().join("");

const wheels = [...new Set([...SAFE_WORDS].filter((word) => word.length === WHEEL_SIZE).map(letterKey))];

const ranked = wheels
    .map((wheel) => ({ wheel, pool: dictionaryWordsFrom(wheel).length }))
    .filter((entry) => entry.pool >= MIN_POOL)
    // Ascending pool size is the difficulty ramp; alphabetical breaks ties stably.
    .sort((a, b) => a.pool - b.pool || a.wheel.localeCompare(b.wheel));

const body = ranked.map((entry) => `    "${entry.wheel}",`).join("\n");
const poolMin = ranked[0]?.pool ?? 0;
const poolMax = ranked[ranked.length - 1]?.pool ?? 0;

const file = `/**
 * GENERATED by scripts/build-wheels.ts — do not edit by hand.
 *
 * ${ranked.length} six-letter wheels (letter multisets, duplicates allowed) drawn from
 * safe-english-words-3to6.txt, ranked by spellable-pool size ascending.
 * Pool sizes run ${poolMin}..${poolMax}. Array order is the difficulty ladder.
 *
 * Frozen: changing this order changes every generated level and breaks saves.
 * Bump WHEEL_TABLE_VERSION when regenerating on purpose.
 */
export const WHEEL_TABLE_VERSION = 1;

export const WHEELS: readonly string[] = Object.freeze([
${body}
]);
`;

writeFileSync(new URL("../src/game/words/wheels.data.ts", import.meta.url), file);
console.log(`Wrote ${ranked.length} wheels (pool ${poolMin}..${poolMax}) to src/game/words/wheels.data.ts`);
